// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RawPostingsFilter.Persistence;

#nullable disable

namespace RawPostingsFilter.Persistence.Migrations
{
    [DbContext(typeof(RawPostingsDbContext))]
    partial class RawPostingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RawPostingsFilter.Persistence.Entities.RawDuplicateCandidate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("RawPostingsFilter.Persistence.Entities.RawJobPosting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IncomingPosting")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("incoming_posting");

                    b.Property<bool>("IsNormalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_normalized");

                    b.Property<bool>("IsSpamOrAd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_spam_or_ad");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("RawText")
                        .HasDatabaseName("ix_raw_job_postings_raw_text_trgm")
                        .HasFilter("\"raw_text\" IS NOT NULL AND \"is_normalized\" = false");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RawText"), new[] { "gin_trgm_ops" });

                    b.ToTable("raw_job_postings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
